### PR TITLE
DMVP: Changed python3.7 to 3.11

### PR DESCRIPTION
**Pull request by NJ3rsey**

### CODE REVIEW

**Comment by NJ3rsey** [comment]
@viktoryathegreat Please review this little PR

**Review by viktoryathegreat — APPROVED** [review]

**Review by viktoryathegreat — APPROVED** [review]
LGTM

**Comment by NJ3rsey** [comment]
@viktoryathegreat 🥺

**Comment by NJ3rsey** [comment]
@aramkarapetian Hey, could this be merged?

**Comment by aramkarapetian** [comment]
@NJ3rsey will take a look, thanks for PR.

**Review by aramkarapetian — APPROVED** [review]
LGTM

**Pull request merged**
